{% set name = "detidelevel" %}
{% set version = "1.0.5" %}
# {% set sha256 = "1af0d444b2299ab16a0963d7a8fa1a66a0203b17c628d0bd3fe32a685d943298" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub remove the line above
  # uncomment the line below and modify as needed
  # url: https://github.com/simplejson/{{ name }}/archive/{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - hatchling
  run:
    - python
    - pandas
    - statsmodels

test:
  imports:
    - detidelevel

about:
  home: https://github.com/mullenkamp/detidelevel
  license: Apache License 2.0
  license_family: APACHE
  summary: A Python package to remove tidal signals in water level time series.
  description: ""
  doc_url: ''
  dev_url: ''
